title: MEME
author: Hamza
email: Email@email.com
description: > # this means to ignore newlines until "baseurl:"
  Link in bioscription, like comment subscribe.

# social links
twitter_username: your-twitter-handle
github_username:  Hamza-AYJ

show_excerpts: true # set to false to remove excerpts on the homepage

theme:minima
